
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.DogsScalarFieldEnum = {
  id: 'id',
  src: 'src',
  type: 'type',
  alt: 'alt',
  width: 'width',
  height: 'height',
  title: 'title',
  description: 'description',
  data_tags: 'data_tags',
  date: 'date',
  category: 'category',
  active: 'active',
  poster: 'poster'
};

exports.Prisma.UsersScalarFieldEnum = {
  id: 'id',
  username: 'username',
  password: 'password',
  type: 'type',
  fname: 'fname',
  lname: 'lname',
  email: 'email'
};

exports.Prisma.Bbq_claimScalarFieldEnum = {
  id: 'id',
  recipe_id: 'recipe_id',
  guest_id: 'guest_id',
  created_at: 'created_at'
};

exports.Prisma.Bbq_guestScalarFieldEnum = {
  id: 'id',
  name: 'name',
  phone: 'phone',
  token: 'token',
  created_at: 'created_at'
};

exports.Prisma.Bbq_recipeScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  title: 'title',
  blurb: 'blurb',
  host_note: 'host_note',
  category: 'category',
  effort: 'effort',
  source: 'source',
  recipe_url: 'recipe_url',
  body: 'body',
  claim_cap: 'claim_cap',
  pairs_with: 'pairs_with',
  reserved_for: 'reserved_for',
  sort_order: 'sort_order'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.dogsOrderByRelevanceFieldEnum = {
  src: 'src',
  type: 'type',
  alt: 'alt',
  title: 'title',
  description: 'description',
  data_tags: 'data_tags',
  date: 'date',
  category: 'category',
  poster: 'poster'
};

exports.Prisma.usersOrderByRelevanceFieldEnum = {
  username: 'username',
  password: 'password',
  type: 'type',
  fname: 'fname',
  lname: 'lname',
  email: 'email'
};

exports.Prisma.bbq_guestOrderByRelevanceFieldEnum = {
  name: 'name',
  phone: 'phone',
  token: 'token'
};

exports.Prisma.bbq_recipeOrderByRelevanceFieldEnum = {
  slug: 'slug',
  title: 'title',
  blurb: 'blurb',
  host_note: 'host_note',
  recipe_url: 'recipe_url',
  body: 'body',
  pairs_with: 'pairs_with'
};
exports.bbq_recipe_category = exports.$Enums.bbq_recipe_category = {
  appetizer: 'appetizer',
  meat_dish: 'meat_dish',
  meat_side: 'meat_side',
  starchy_side: 'starchy_side',
  veggie_side: 'veggie_side',
  salad: 'salad',
  dessert: 'dessert',
  pantry: 'pantry'
};

exports.bbq_recipe_effort = exports.$Enums.bbq_recipe_effort = {
  easy: 'easy',
  medium: 'medium',
  project: 'project'
};

exports.bbq_recipe_source = exports.$Enums.bbq_recipe_source = {
  family: 'family',
  heb: 'heb'
};

exports.Prisma.ModelName = {
  dogs: 'dogs',
  users: 'users',
  bbq_claim: 'bbq_claim',
  bbq_guest: 'bbq_guest',
  bbq_recipe: 'bbq_recipe'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
